edit group report
report update

Adding team meeting notes 6, 7, 8, 9

fix folder

delete no longer need file

Create checkmarx-one.yml

Update report

Update Group Report .docx

Update Group Report .docx

Group report 17:37

Added a sentence in the summary and changed a couple grammar errors

team meeting notes 10

add design doc url in game

update video url.pdf

added peer review scores

add Build V1.0 Releases

Upload testing doc

Update github actions for V1.0

Update github actions for V1.0 fix

Update Build,ReleaseGame(nuitka).yml

Updated requirement analysis

Peer assessment scores

add final build update log for V1.0 release

Group report update

bid bug fix

Revert "bid bug fix (didnt work :(

This reverts commit 798b151fb7b845e7a36616c24e35151e873686de.

Design doc upload

add the .nojekyll file.

to tells GitHub Pages Don't try to be clever with Jekyll; just serve the HTML, CSS, JS, and image files

Risk analysis update and report

Delete .ds_store

Formatting code

merge Used resources.docx into report.docx

upload level testing doc 2

try fix logging maximum recursion depth bug3

try fix logging maximum recursion depth bug2

try fix logging maximum recursion depth bug

Traceback (most recent call last):
  File "logging\__init__.py", line 1153, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1153, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1153, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1153, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1153, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1153, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1153, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1153, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1153, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1153, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1153, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1153, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1153, in emit

bug fix ???